export class LankanPlacesDeatails {
  public static placesDetails = [
    {
      "id": 1,
      "place":'Bentota',
      "imagePath":'./assets/images/packageImages/1',
      "backgroundImage":"1.jpg",
      "description":'Bentota is famed as the prime beach resort of the south-western and southern coastal belts of Sri Lanka. South of the city of Colombo, the city of Kalutara with its fine beach is the gateway to south western and southern bay beaches. Kalutara is the next popular beach after Bentota. The Beruwala Bay Beach that is found just before reaching Aluthgama at the Bentota Bridge and Bentota Bay Beach just over the bridge is the most popular twin beaches along the coast. The coast towards the further South too is replete with lovely topical beaches making it ideal for a perfect beach holiday with the sun and sand.',
    },
    {
      "id": 2,
      "place":'Hikkaduwa',
      "imagePath":'./assets/images/packageImages/1',
      "backgroundImage":"2.jpg",
      "description":'Hikkaduwa beach is a very popular destination to international tourists. It is 98 kilometers south from Colombo. It is a beautiful beach where you can relax, enjoy the sun and have the option of surfing, snorkeling or scuba diving. Being the site of the famed coral garden, glass bottomed boats are available on hire and visitors can explore the underwater fantasies. It is also an internationally popular destination for board-surfing and surfing. Hikkaduwa is also well known for its upbeat night life and delicious roadside cuisine which presents a fusion of Sri Lankan and western food. The extraordinarily attractive beach of Hikkaduwa is a place of fun and excitement and always has something for everyone.',
    },
    {
      "id": 3,
      "place":'Mirissa',
      "imagePath":'./assets/images/packageImages/1',
      "backgroundImage":"3.jpg",
      "description":'Mirissa Beach is located in almost the southernmost place of Sri Lanka. It is a romantic beach in a beautiful half-circle bay with adjacent other small, “robinson” beaches. Although it belongs to the list of Sri Lankan most famous beaches, it is relatively less visited than beaches situated more in the west of the island.',
    },
    {
      "id": 4,
      "place":'Colombo',
      "imagePath":'./assets/images/packageImages/1',
      "backgroundImage":"4.jpg",
      "description":'Colombo, Sri Lanka‘s bustling commercial hub, is located on the country’s west coast and with a population of between 800,000 and one million (estimates vary) is by far the country’s biggest city, as well as the most developed. Its natural harbor at the mouth of the Kelani River was a magnet for successive traders and conquerors – initially the Arab merchants, then Portuguese, Dutch and British imperialists. The city is a jarring mix of old and new, with a central cluster of high-rise office blocks and hotels overshadowing red-tiled colonial-era buildings and sprawling street markets which overflow with high-piled fruit and vegetables, colorful silks and cottons, and deliciously fragrant spices. On its crowded streets stand places of worship, symbolic of Sri Lanka‘s multiethnic heritage: graceful Buddhist viharas (temples), for instance, stand close to extravagant temples encrusted with Hindu statuary, along with Muslim mosques with minarets scattered along Colombo’s streets. Its population is swollen by some 400,000 plus commuting workers during the day and is virtually empty after nightfall. There is a lively nightlife at a number of International standard hotels, clubs, pubs and dining venues while it is limited mainly to the high end customers. During the day, Colombo’s colorful street markets, colonial-era buildings, museums and galleries, churches, mosques and temples, and the lovely Viharamahadevi Park with it beautiful trees, makes it a great place to explore on foot.',
    },
    {
      "id": 5,
      "place":'Yala',
      "imagePath":'./assets/images/packageImages/2',
      "backgroundImage":"3.jpg",
      "description":'Yala National Park is well recognized as one of the best park in the world to observe leopards. Yala National Park has a variety of ecosystems including moist monsoon forests, dry monsoon forests, semi deciduous forests, thorn forests, grasslands, fresh water and marine wetlands, and sandy beaches.',
    },
    {
      "id": 6,
      "place":'Kalpitiya',
      "imagePath":'./assets/images/packageImages/3',
      "backgroundImage":"1.jpg",
      "description":'Kalpitya is located in the North Western Province, Puttalam, of Sri Lanka. The city consists of a total 14 islands that are a crown for its stunning natural beauty. Kalpitya is also famous for its oceanic beauty. It is definitely showing its true potential under great refinement and development, which is ultimately leading it to become a relentless tourist attraction. Sport activities like Kite surfing, Stand up Paddling, Diving, Skate boarding and simple surfing are the norm around the islands. Tourists can experience the Blue Ocean, sandy beaches and arid plains from the skies before they get tired and enjoy the fine Sri Lankan cuisine at the customer pleasing resorts and restaurants.',
    },{
      "id": 7,
      "place":'Wilpattu',
      "imagePath":'./assets/images/packageImages/3',
      "backgroundImage":"2.jpg",
      "description":'Wilpattu National Park’s varying natural habitats; coastal belt, natural lakes (villus), rocky outcrops, scrublands, open grasslands and dense forest provide for numerous species of animals. Among the species are 31 mammals. The biggest draws in Wilpattu are Leopards (Panthera pardus kotiya) and Sloth bears (Melursus ursinus). Apart from those two mammals are Asian Elephants (Elephas maximus), Spotted Deer, and Barking Deer, jackals, sambhur, barking deer, mouse deer Wild Pig, Water Buffalo (Bubalus bubalis) and Mugger Crocodiles.',
    },
    {
      "id": 8,
      "place":'Sigiriya / Dambulla',
      "imagePath":'./assets/images/packageImages/3',
      "backgroundImage":"3.jpg",
      "description":'Sigiriya is one of the most valuable historical monuments of Sri Lanka. Referred by locals as the Eighth Wonder of the World this ancient palace and fortress complex has significant archaeological importance and attracts thousands of tourists every year. It is probably the most visited tourist destination of Sri Lanka.The palace is located in the heart of the island between the towns of Dambulla and Habarane on a massive rocky plateau 370 meters above the sea level. Sigiriya rock plateau, formed from magma of an extinct volcano, is 200 meters higher than the surrounding jungles. Its view astonishes the visitors with the unique harmony between the nature and human imagination. The fortress complex includes remnants of a ruined palace, surrounded by an extensive network of fortifications, vast gardens, ponds, canals, alleys and fountains. The surrounding territories of Sigiriya were inhibited for several thousand years. Since 3th century BC the rocky plateau of Sigiriya served as a monastery. In the second half of the 5th century king Kasyapa decided to construct a royal residence here. After his death Sigiriya again became a Buddhist monastery until the 14th century, when it was abandoned. The main entrance is located in the northern side of the rock. It was designed in the form of a huge stone lion, whose feet have survived up to today but the upper parts of the body were destroyed. Thanks to this lion the palace was named Sigiriya.',
    },
    {
      "id": 9,
      "place":'Kandy',
      "imagePath":'./assets/images/packageImages/3',
      "backgroundImage":"4.jpg",
      "description":'Kandy, the last royal capital of Sri Lanka is a major tourist destination. (115km from Colombo at 465 meters above sea level). Famous for the Temple of the Tooth relic and many other temples the city could be called the cultural capital of the island. Kandy Perahera, the pageant of the temple of tooth relic Buddha’s secret tooth is kept, held either in July or August each year to parade the golden caskets is a must see itenary if one is visiting Sri Lanka during these months. The final night procession is the most spectacular event of the country. More than 50 elephants parade the city accompanied by the drummers, dancers and chieftains.',
    },
    {
      "id": 10,
      "place":'Negombo',
      "imagePath":'./assets/images/packageImages/3',
      "backgroundImage":"5.jpg",
      "description":'Negombo is located approximately 38 km north of the commercial capital of Colombo in Sri Lanka It is located at the mouth of the Negombo lagoon. The beach bears most of the major resorts in the Western Coast is Negombo. The wide sandy beaches and the safe sea are the main attractions of Negombo and it is perfectly located within 7 km from the Bandaranaike International Airport in Katunayake, Sri Lanka.',
    },
    {
      "id": 11,
      "place":'Nuwara Eliya',
      "imagePath":'./assets/images/packageImages/4',
      "backgroundImage":"2.jpg",
      "description":'Situated at around 2000m above sea level and surrounded by lush tea plantations. Nuwara Eliya bears the main hill resorts of Sri Lanka and the heart of the tea industry. Once a pleasure retreats of the European planters the town is still very much an English town with many English style bungalows and buildings. Nuwara Eliya offers many activities for tourists including visits to tea plantations golf, horse riding, boating, hiking and of course exploring the beauty of the landscaped gardens, waterfalls and plateaus.',
    },
    {
      "id": 12,
      "place":'Ella',
      "imagePath":'./assets/images/packageImages/4',
      "backgroundImage":"3.jpg",
      "description":'Ella, often described as ‘’lonely planet’’ and ‘’waterfall’’, is a congested town located in Sri Lanka. Ella is pure natural beauty, with its waterfalls, greenery, and hills, it is just jaw-dropping. It has views that one hasn’t witnessed before, scenes one has not seen before and nature one has not felt before. Ella is the perfect place to go to if one wants to refresh the brain. It has many famous places and has been under the attention of tourist for a decent amount of time now.',
    },
    {
      "id": 13,
      "place":'Mahiyangana',
      "imagePath":'./assets/images/packageImages/6',
      "backgroundImage":"3.jpg",
      "description":'Dambana located 19km north east of Mahiyangana bordering the Maduru Oya Sanctuary is home to the indigenous “Vedda” community numbering close to 1000 individuals. The natural habitat of these people, whose livelihood once depended solely on hunting, was confined to the forest. However during the recent decades, they have been shifting in a slow transformation into Chena dry land for cultivation. Over and above the transition, these aborigines of Sri Lanka have begun to intermarry with the Sinhalese villagers living in the region surrounding Dambana. The total extinction of their traditions of hunting for food, cooking in open fire with a group, collecting Bees Honey, their songs and dances has now become a rare possibility.',
    },
    {
      "id": 14,
      "place":'Udawalawa',
      "imagePath":'./assets/images/packageImages/6',
      "backgroundImage":"5.jpg",
      "description":'Udawalawe Nationa Park is located approximately 200 km south-east of Colombo city and is a major eco tourism destination in Sri Lanka. The 30,821 hectares dry zone game park has an annual rainfall of 1524 mm and an average temperature of 29.4°C. It is most famous for the many elephants that live there (about 400 in total). During a visit, it is not unusual to see whole herds of adults and young elephants– feeding or bathing and playing in the water! In addition to this main attraction, the park is home to many water buffalo, water monitor lizards, sambar deer, monkeys and the occasional leopard, as well as being an exciting location for bird enthusiasts.',
    },
    {
      "id": 15,
      "place":'Pasikuda',
      "imagePath":'./assets/images/packageImages/7',
      "backgroundImage":"5.jpg",
      "description":'Pasikuda is known to have one of the longest stretches of shallow coastline in the world and people can walk several hundred meters into the sea because the water is only a few inches deep. If you wish to learn swimming, Passikudah is the best and protected place. You have several options to choose – lie down on the beach and relax in peace & harmony, or enjoy a long walk along the beautiful unspoilt beach, or accompany your children play in the shallow waters or join your peers in swimming & playing water games or even have a boat ride.',
    },
    {
      "id": 16,
      "place":'Trincomalee',
      "imagePath":'./assets/images/packageImages/7',
      "backgroundImage":"6.jpg",
      "description":'Trincomalee, one of the finest natural deep-water harbors in the world is located 257 km north-east of Colombo, which is considered as the commercial hub of Sri Lanka. Trincomalee is home to the fine beaches of Nilaveli, Uppuveli and the off-shore Pigeon Island. Recently Trincomalee has become popular as a Whale Watching destination as well. The Dive centres at Nilaveli and Uppuveli offer tourists the opportunity to enjoy their holidays in diving, snorkeling and swimming. The Trincomalee district, referred as Gokanna or Gokarna in the historical chronicles and inscriptions, is studded with a multitude of ruins of ancient Buddhist temples and is considered a major Buddhist cultural and archaeological site of Sri Lanka. The seven hot springs at Kanniya located a mere 8km from Trincomalee attract regular crowds throughout the year in view of the therapeutic properties of the water as well as the varying temperatures from one well to the other.',
    },
    {
      "id": 17,
      "place":'Nilaveli',
      "imagePath":'',
      "backgroundImage":"",
      "description":'One of the wonderful places that you should not miss in Trincomalee is the Nilaveli Beach, which is described as one of the finest beaches in Sri Lanka, perhaps in Asia. The long and wide beach with the brilliant white sand gives you an unforgettable experience. Many people come to Nilaveli beach to take a break and relaxation from the hectic lives as it is less crowded compared to the beaches in the west and the south. You would be lost at Nilaveli beach in its quite serene and the crystal clear blue water. It is also very popular among sun worshipers and an ideal place for water sports like scuba diving.',
    },
    {
      "id": 18,
      "place":'Anuradhapura',
      "imagePath":'./assets/images/packageImages/8',
      "backgroundImage":"2.jpg",
      "description":'Sri Lanka’s historical chronicle, The Mahavansa, records that Anuradhapura first became the capital of ancient Lanka in 4th Century BC, during the reign of “King Pandukhabaya”. The King is attributed with designing the city, developing a core town and even surrounding suburbs based on a highly complex plan. Anuradhapura came into prominence after Buddhism was introduced to the island in the 3rd Century BC during the reign of “King Devanampiya Tissa”. He built the country’s first “stupa” here, the “Thuparama”, which is said to house a relic of the Buddha, his right collarbone. King Tissa also arranged for the planting of the sacred Bo sapling brought to the country by “Sangamitta Thero”, daughter of Emperor Asoka of India. This is today the venerated “Sri Maha Bodhi”, which is considered the oldest living tree in the world.',
    },
    {
      "id": 19,
      "place":'Polonnaruwa',
      "imagePath":'./assets/images/packageImages/8',
      "backgroundImage":"3.jpg",
      "description":'Most commonly referred to as Sri Lanka’s second ancient capital, the city of Polonnaruwa is nevertheless a magnificently preserved city with rich archaeological monuments and natural beauty. Located in Sri Lanka’s North Central Province, Polonnaruwa has both its ancient city; an adjoining “old town” as well as a “new town” located about 6km away. The archaeological sites are in a compact layout, within easy distance of each other, and tours are easily arranged either on foot or more popularly explored on bicycle. As in Anuradhapura, Polonnaruwa too has its share of Buddhist sites, and tour buses of pilgrims can be often seen visiting the stupas and monasteries. But Polonnaruwa also boasts an impressive array of ruined palaces and courtyards, pleasure gardens and intricate networks of bathing tanks, as well as carvings and sculptures and a rich display of artistry. The ancient city was declared a World heritage Site by UNESCO in 1982.',
    },
    {
      "id": 20,
      "place":'Habarana',
      "imagePath":'',
      "backgroundImage":"",
      "description":'xxxxx',
    },
    {
      "id": 21,
      "place":'Thissamaharama',
      "imagePath":'',
      "backgroundImage":"",
      "description":'xxxxx',
    }
  ]
}
