export class PackageData {
  public static packageList= [
    {
      "id":1,
      "days":5,
      "mainTopic":'4 NIGHTS 5 DAYS PACKAGE',
      "subTopic":'Beach Honeymoon Tour',
      "locationCovered":["Bentota","Hikkaduwa","Mirissa","Colombo"],
      "ativitiesCovered":["Visit Kande Vihare","Visit to Turtle Farm","Visit to Gem Museum","Madu Ganga Tour","Whale and dolphin watching at Mirissa","Visit Coral Gardens","Night out in a Club","City tour and Shopping in Colombo"],
      "inclusions":["Return Air Ticket in Sri Lankan airlines","Airport Pick up and Drop off","Private luxury Vehicle (Air Conditioned)","Fuel and Insurance for the vehicle","Accommodation on Full board and half board basis in Star class luxurious hotels","Extra meals on the way from A class restaurant","Drinking water bottles for entire tour","Private English speaking Guide","Entrance fees","Charges for Safari Jeeps","Charges for Whale and dolphin watching"],
      "imagePath":'./assets/images/packageImages/1',
      "backgroundImage":"package.jpg",
      "activityListId":1,
      "summary":"Beach Honeymoon tour package, we offer you 5 days of beautiful beach who are the beach lovers. This tour offers you many beautiful beach activities like Jet Skis, Turtle farm, scuba dive, coral reef, whale and dolphin and many more… with Ayurveda spa treatment. This 5 days tour package will explore 4 beautiful destinations.",
      "sliderImages":["1.jpg","2.jpg","3.jpg","4.jpg"]
    },

    {
      "id":2,
      "days":6,
      "mainTopic":'5 NIGHTS 6 DAYS PACKAGE',
      "subTopic":'Beach Package',
      "locationCovered":["Bentota","Mirissa","Yala","Hikkaduwa","Colombo"],
      "ativitiesCovered":["Visit Kande Vihare","Visit to Turtle Farm","Visit to Gem Museum","Madu Ganga Tour","Whale and dolphin watching at Mirissa","Yala Safari","Visit Coral Gardens","Visit Tsunami Museum","Night out in a Club","City tour and Shopping in Colombo"],
      "inclusions":["Return Air Ticket in Sri Lankan airlines","Airport Pick up and Drop off","Private luxury Vehicle (Air Conditioned)","Fuel and Insurance for the vehicle","Accommodation on Full board and half board basis in Star class luxurious hotels","Extra meals on the way from A class restaurant","Drinking water bottles for entire tour","Private English speaking Guide","Entrance fees","Charges for Safari Jeeps","Charges for Whale and dolphin watching"],
      "imagePath":'./assets/images/packageImages/2',
      "backgroundImage":"package.jpg",
      "activityListId":2,
      "summary":"6 Days Tour Package We offers you a experiences of beautiful beach areas with many activities. Bentota known as golden sandy beach, Mirissa known as whale and Dolphin, Snorkeling, Hikkaduwa known as coral reef, scuba dive and wildlife experience and many more.",
      "sliderImages":["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg"]
    },
    {
      "id":3,
      "days":6,
      "mainTopic":'5 NIGHTS 6 DAYS PACKAGE',
      "subTopic":'',
      "locationCovered":["Kalpitiya","Wilpattu","Sigiriya","Kandy","Negombo"],
      "ativitiesCovered":["Explore Kalpitiya","Whale watching in Kalpitiya","Safari at Wilpattu","Anuradhapura Ruins","Dambulla Golden cave temple","Climb Sigiriya Rock","Hiriwadunna village tour","Spice gardens","Tooth relic temple","Cultural show","City tour in Kandy","Peradeniya Botanical Gardens","Pinnawala elephant orphanage","Night out in a Club","City tour and Shopping in Negombo"],
      "inclusions":["Return Air Ticket in Sri Lankan airlines","Airport Pick up and Drop off","Private luxury Vehicle (Air Conditioned)","Fuel and Insurance for the vehicle","Accommodation on Full board and half board basis in Star class luxurious hotels","Extra meals on the way from A class restaurant","Drinking water bottles for entire tour","Private English speaking Guide","Entrance fees","Charges for Safari Jeeps","Charges for Whale and dolphin watching"],
      "imagePath":'./assets/images/packageImages/3',
      "backgroundImage":"package.jpg",
      "activityListId":3,
      "summary":"6 Days Tour Package We offers you a experiences of beautiful beach areas with many activities. Kalpitiya known as Kitesufring, whale and Dolphin and wildlife experience and many more.",
      "sliderImages":["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg"]
    },
    {
      "id":4,
      "days":7,
      "mainTopic":'6 NIGHTS 7 DAYS PACKAGE',
      "subTopic":'Honeymoon Package',
      "locationCovered":["Kandy","Nuwaraeliya","Ella","Colombo"],
      "ativitiesCovered":["Pinnawala Elephant orphanage","Cultural Show","Kandy Tooth Relic Temple","City tour and shopping in Kandy","Tea Factory Visit","Gregory’s Lake Visit","Victoria Park Visit","Climb Piduruthalagala","Visit Moon Plains","Spa treatment","Ravana Falls","Nine Arch Bridge","Night out in a Club","City tour and Shopping in Colombo"],
      "inclusions":["Return Air Ticket in Sri Lankan airlines","Airport Pick up and Drop off","Private luxury Vehicle (Air Conditioned)","Fuel and Insurance for the vehicle","Accommodation on Full board and half board basis in Star class luxurious hotels","Extra meals on the way from A class restaurant","Drinking water bottles for entire tour","Private English speaking Guide","Entrance fees","Charges for Safari Jeeps","Charges for Whale watching"],
      "imagePath":'./assets/images/packageImages/4',
      "backgroundImage":"package.jpg",
      "activityListId":4,
      "summary":"Honeymoon tour package, we offer you 7 days of beauty of around the Ceylon (Sri Lanka) with Ayurveda spa treatment and Nightlife in Colombo. This 7 days tour package will explore 4 beautiful destinations.",
      "sliderImages":["1.jpg","2.jpg","3.jpg","4.jpg"]
    },
    {
      "id":5,
      "days":7,
      "mainTopic":'6 NIGHTS 7 DAYS PACKAGE',
      "subTopic":'',
      "locationCovered":["Kandy","Nuwaraeliya","Yala","Mirissa","Colombo"],
      "ativitiesCovered":["Pinnawala Elephant orphanage","Kandy Tooth Relic Temple","City tour in Kandy","Tea Factory Visit","Visit Victoria Park","Visit Gregory’s Lake","Worlds End – Horton Plains and Baker’s falls","Spa treatment","Climb Piduruthalagala","Yala Safari","Whale watching and Dolphin watching","City tour in Colombo","Night out in a Club","Shopping in Colombo"],
      "inclusions":["Return Air Ticket in Sri Lankan airlines","Airport Pick up and Drop off","Private luxury Vehicle (Air Conditioned)","Fuel and Insurance for the vehicle","Accommodation on Full board and half board basis in Star class luxurious hotels","Extra meals on the way from A class restaurant","Drinking water bottles for entire tour","Private English speaking Guide","Entrance fees","Charges for Safari Jeeps","Charges for Whale watching"],
      "imagePath":'./assets/images/packageImages/5',
      "backgroundImage":"package.jpg",
      "activityListId":5,
      "summary":"We tail made this package with the places where most of the honeymoon would like to chillout. You will be taking to the most beautiful areas of Sri Lanka. Kandy is known as the kingdom of Buddhist secrete tooth relic. Nuwara Eliya where it is named “Little England” hill side of Sri Lanka. You will find all British type houses and buildings, gardens, waterfalls, tea plantations and many more… This tour offers you the real deal – a perfect blend of scenic nature spots of all terrains, the best cultural experiences you will find, as well as wildlife7 days package will offer you valuable vacation with many activities by covered 5 destinations.",
      "sliderImages":["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg"]
    },
    {
      "id":6,
      "days":9,
      "mainTopic":'8 NIGHTS 9 DAYS PACKAGE',
      "subTopic":'',
      "locationCovered":["Kalpitiya","Sigiriya","Mahiyangana","Thissamaharama","Udawalawa","Colombo"],
      "ativitiesCovered":["Explore Kalpitiya","Whale watching in Kalpitiya","Safari at Minneriya","Climb Sigiriya Rock","Hiriwadunna village tour","Visit Dambulla cave temple","Safari at Wasgamuwa","Visit Rathna Ella","Visit Sorabora Lake","Visit Maduru Oya","Visit Veddha Village","Safari at Yala","Udawalawa Safari","Night out in a Club","City tour and Shopping in Colombo"],
      "inclusions":["Return Air Ticket in Sri Lankan airlines","Airport Pick up and Drop off","Private luxury Vehicle (Air Conditioned)","Fuel and Insurance for the vehicle","Accommodation on Full board and half board basis in Star class luxurious hotels","Extra meals on the way from A class restaurant","Drinking water bottles for entire tour","Private English speaking Guide","Entrance fees","Charges for Safari Jeeps","Charges for Whale watching"],
      "imagePath":'./assets/images/packageImages/6',
      "backgroundImage":"package.jpg",
      "activityListId":6,
      "summary":"We offer you 9 days tour package experience of wildlife in Sri Lanka, and many more attraction activities like whale and dolphin watching, Climbing Lion Rock, lakes. Colombo nightlife and many more. This 9 days tour package will explore 6 beautiful destinations.",
      "sliderImages":["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg"]
    },
    {
      "id":7,
      "days":10,
      "mainTopic":'9 NIGHTS 10 DAYS PACKAGE',
      "subTopic":'Golden Triangle',
      "locationCovered":["Kandy","Habarana","Sigiriya","Polonnaruwa","Pasikuda","Trinco","Anuradhapura","Negombo"],
      "ativitiesCovered":["Pinnawala Elephant Orphanage","Visit Saradiyel Village","Peradeniya Botanical Gardens","Visit Tooth Relic Temple","Cultural Show","City tour and Shopping in Kandy","Spice gardens","Dambulla cave temple","Climb Sigiriya Rock","Safari at Minneriya","Hiriwadunna village tour","Ruins at Polonnaruwa","Pasikuda Beach","Marble Beach","Kinniya Bridge","Koneshwaram Temple","Kanniya Hot Spring Wells","Ruins at Anuradhapura","Ancient city visit Anuradhapura","Climb Mihinthale Rock","Night out in a Club","City tour and Shopping in Negombo"],
      "inclusions":["Return Air Ticket in Sri Lankan airlines","Airport Pick up and Drop off","Private luxury Vehicle (Air Conditioned)","Fuel and Insurance for the vehicle","Accommodation on Full board and half board basis in Star class luxurious hotels","Extra meals on the way from A class restaurant","Drinking water bottles for entire tour","Private English speaking Guide","Entrance fees","Charges for Safari Jeeps"],
      "imagePath":'./assets/images/packageImages/7',
      "backgroundImage":"package.jpg",
      "activityListId":7,
      "summary":"We offer you 10 Days tour Package “Golden Triangle” with many attraction actives like Elephant Orphanage, experience of Sri Lankan culture and history, wildlife, beautiful beach areas with many more. This 10 days tour package will explore 8 beautiful destinations.",
      "sliderImages":["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg"]
    },
    {
      "id":8,
      "days":11,
      "mainTopic":'10 NIGHTS 11 DAYS PACKAGE',
      "subTopic":'Around the Island',
      "locationCovered":["Negombo","Anuradhapura","Polonnaruwa","Sigiriya","Kandy","Nuwaraeliya","Ella","Yala","Colombo"],
      "ativitiesCovered":["Negombo City Tour and Shopping","Ruins and temples Anuradhapura","Ruins at Polonnaruwa","Dambulla Cave Temple","Climb Sigiriya Rock","Hiriwadunna village tour","Visit Spice Gardens","Cultural Show","City tour and Shopping at Kandy","Kandy tooth relic temple","Peradeniya botanical gardens","Tea Factory visit","World’s end tour – Horton Plains and Baker’s falls","Visit Gregory’s lake","Visit Victoria Park","Climb Piduruthalagala","Visit Ambewel farm and Strawberry farm","Visit nine arch bridge","Visit Rawana Falls","Visit Little Adam’s peaks","Visit Ella Rock","Safari at Yala","Night out in a Club","City tour and Shopping in Colombo"],
      "inclusions":["Return Air Ticket in Sri Lankan airlines","Airport Pick up and Drop off","Private luxury Vehicle (Air Conditioned)","Fuel and Insurance for the vehicle","Accommodation on Full board and half board basis in Star class luxurious hotels","Extra meals on the way from A class restaurant","Drinking water bottles for entire tour","Private English speaking Guide","Entrance fees","Charges for Safari Jeeps"],
      "imagePath":'./assets/images/packageImages/8',
      "backgroundImage":"package.jpg",
      "activityListId":8,
      "summary":"Around the Island tour package, we offer you and exiting 11 days of pure and utter bliss visiting, where our mother island exclusive, high recommended area to be visited. This tour offers you the real deal – a perfect blend of scenic nature spots of all terrains, the best cultural experiences you will find, as well as wildlife in all 4 corners of the island. The 11-day tour package will explore over 9 destinations.",
      "sliderImages":["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg","9.jpg"]
    }
  ];
}
